name: Continuous Integration

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']

    name: PHP ${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer:v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: install dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: dump autoload
        run: composer dump-autoload

      - name: check syntax
        run: find src -name '*.php' | xargs -n 1 -P4 php -l

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
