name: Deployment

on:
  push:
    branches: [ deployment-action ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - uses: actions/setup-node@v1.1.0
      with:
        version: 12.x

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        npm install

    - name: Create package
      run: gulp dist --compressedName agb-connector

    - name: Copy package to remote server
      run: scp agb-connector.zip ${{secrets.DESTINATION}}
      
    #- name: Extract package
    #- name: rsync    
            
